### ISSUE TITLE
can't create new author and set it on post

### ISSUE THREAD

**Issue by czpython** [aldryn/aldryn-newsblog#119]
When creating a new post, if instead of selecting an existing author I click on the "+" to create one, once it's created and I save the post, it uses the current user as author instead of the selected author.

https://www.dropbox.com/s/z8hw4wkekti2nd8/newsblog-issue-3.mov?dl=0

**Comment by mkoistinen** [comment]
Thanks for this, @czpython. Crystal clear now =)

**Comment by mkoistinen** [comment]
Hmmm, I'm unable to reproduce this with the current master. Like you, I've recorded this: http://cl.ly/3h2N1l410X1s. Can you help me ID the differences between my testbed and your project? Could this be related to Parler?
