### ISSUE TITLE
fix translated strings

### ISSUE THREAD

**Issue by stefanfoulis** [aldryn/aldryn-newsblog#120]
fix variable substitution (e.g https://github.com/aldryn/aldryn-newsblog/blob/016a8c3c3a871961f1f6151a80f3f0149d527865/aldryn_newsblog/models.py#L187). Using  ``.format()`` probably will not work here. It needs to be with ``%`` and outside of the ``_()``. https://docs.djangoproject.com/en/1.7/topics/i18n/translation/

**Comment by mkoistinen** [comment]
Oops, well-spotted.
