### ISSUE TITLE
consistent template and plugin naming

### ISSUE THREAD

**Issue by stefanfoulis** [aldryn/aldryn-newsblog#122]
In some places we use ``Article`` in some ``Entry``.

* plugin template names
* plugin names
* plugin model names
* ....?

**Comment by stefanfoulis** [comment]
I vote for ``Article`` since it fits well for both News and Blog and is less generic than Entry.

**Comment by mkoistinen** [comment]
+1 Article throughout

**Comment by mkoistinen** [comment]
This and #90 and #126 should be fixed at the same time.

**Comment by mkoistinen** [comment]
Closed by #128
