### ISSUE TITLE
More strict dependency versions

### ISSUE THREAD

**Issue by mikek** [aldryn/aldryn-newsblog#14]
For example, we rely on a class decoration feature which is present in reversion>=1.8.2. (I've learned it the hard way during the test project setup for this app.) There might be other similar issues. Let's use some version range specifiers where we can, but not to strict to allow other apps  in the hypothetical project to work.

**Comment by mkoistinen** [comment]
@mikek Can we close this now?

**Comment by mikek** [comment]
@mkoistinen, as most fragile dependency versions are pinned now, we can probably close this.

**Comment by mkoistinen** [comment]
@mikek bear in mind that django CMS itself uses 1.8.2 for Django 1.6. If you use reversion features from later versions you may find yourself in a bind.

**Comment by mkoistinen** [comment]
Closing this as nearly all dependencies are pinned at this point.
