### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by piotrjakimiak** [aldryn/aldryn-newsblog#173]
Hi, 

I need to add comments to aldryn-newsblog, are You intrested in adding it as part of newsblog?

What i want to create is:
* adding/editing comments 
* comments moderation
* some spam filters

**Comment by mkoistinen** [comment]
We're using [aldryn-disqus](https://github.com/aldryn/aldryn-disqus) for comments. Is this an option for you? If not, we'd happily accept a PR so long as it is an optional feature.

**Comment by piotrjakimiak** [comment]
I close issue for now. I've done it different way.

**Comment by Tellthebell1** [comment]
Loan fees and interest rates are determined solely by the lender based on the lender’s internal policies, underwriting criteria and applicable law. FinancedFast.com has no knowledge of or control over the loan terms offered by a lender.
<a href="http://www.unitedfinances.com/auto-lenders/">loans online instant approval from UnitedFinances.com"</a>
