### ISSUE TITLE
Exception when running migrations

### ISSUE THREAD

**Issue by tomassommar** [aldryn/aldryn-newsblog#179]
After following the installations instructions according to the github readme, when trying to run migrations for installed on top of django-cms 3.0.13 running on  python 2.7.6, an AttributeError is thrown:

```
File "/local/lib/python2.7/site-packages/aldryn_newsblog/models.py", line 104, in <module>
    class Article(TranslationHelperMixin, TranslatableModel):
  File "/local/lib/python2.7/site-packages/django/utils/encoding.py", line 33, in python_2_unicode_compatible
    if '__str__' not in klass.__dict__:
AttributeError: 'NoneType' object has no attribute '__dict__'
```
Any ideas on what could cause this issue?

**Comment by mkoistinen** [comment]
I wonder if you need to install aldryn-reversion and django-reversion? Can you check?

**Comment by mkoistinen** [comment]
I wonder if you didn't install aldryn-reversion and django-reversion into your ENV or add them to your INSTALLED_APPS? Please check.

**Comment by tomassommar** [comment]
As it turns out, boty django-reversion and aldryn-reversion was installed, but aldryn-reversion wasn't added to INSTALLED_APPS. Also, aldryn_boilerplates wasnt properly configured. Fixing these two errors removed the issue.

However, now have an issue regarding Django 1.7 compatibility in aldryn_boilerplates, which you have also commented on. But let that issue be handled in it's relevant issue tracker :)

So this issue should be marked as resolved.

Thank you for your support!
