### ISSUE TITLE
"_south_new_aldryn_newsblog_article_translation" already exists

### ISSUE THREAD

**Issue by eneftci** [aldryn/aldryn-newsblog#203]
When migrating, getting the following error. 

> aldryn_newsblog:0035_auto__chg_field_articletranslation_language_code__chg_field_newsblogco
FATAL ERROR - The following SQL query failed: CREATE TABLE "_south_new_aldryn_newsblog_article_translation" ("meta_description" text NOT NULL, "meta_title" varchar(255) NOT NULL, "meta_keywords" text NOT NULL, "title" varchar(234) NOT NULL, "search_data" text NOT NULL, "lead_in" text NOT NULL, "language_code" varchar(15) NOT NULL, "id" integer PRIMARY KEY, "master_id" integer, "slug" varchar(255) NOT NULL)
The error was: table "_south_new_aldryn_newsblog_article_translation" already exists

**Comment by chriswedgwood** [comment]
What versions are you running? Can you post your pip freeze into a gist?

**Comment by mkoistinen** [comment]
Hi @eneftci is this still an issue for you? I install this daily and I don't see this issue. Can I close this?

**Comment by eneftci** [comment]
Sorry for the late reply, I believe it was an issue because I tried to migrate the table after patching our prevous code. Thanks!
