### ISSUE TITLE
set migration dependencies

### ISSUE THREAD

**Issue by stefanfoulis** [aldryn/aldryn-newsblog#212]
the migration ``aldryn_newsblog:0011_auto__add_field_article_featured_image`` does not declare a dependency to django-filer. This can cause migration errors if the django-filer tables don't exist yet.

Also check the rest of the migrations for ForeignKeys to any other external apps that might need migration dependencies set (e.g django-cms, aldryn-categories, aldryn-people, django-taggit, ...)

**Comment by intellectronica** [comment]
Fixed in https://github.com/aldryn/aldryn-newsblog/pull/213
