### ISSUE TITLE
"Edit Article..." from Toolbar does not open the correct Article

### ISSUE THREAD

**Issue by stefanfoulis** [aldryn/aldryn-newsblog#223]

**Comment by mkoistinen** [comment]
Unable to reproduce this.

**Comment by kkovrizhenko** [comment]
To reproduce it you need to have at least one article posted , then:
1. Create new article(1)
2. Navigated to another blog article (2) (that was posted first) page
3. Click "Blog" - "Edit article"
- > Edit article with content of last created (1) blog entry is shown
