### ISSUE TITLE
Request For Documentation - Overriding default template

### ISSUE THREAD

**Issue by vdnclodio** [aldryn/aldryn-newsblog#303]
Hi,

Context
----------
&nbsp;&nbsp;&nbsp;&nbsp;I'm using a fresh install of django-cms with aldryn-newsblog. Everything is working really fine.

Problem
----------
&nbsp;&nbsp;&nbsp;&nbsp;Now that everything is working, i would like to customize the look and feel of this new blog engine.
&nbsp;&nbsp;&nbsp;&nbsp;I can override css as usual with bootstrap, but i want to dig a bit further and modify the base template.
&nbsp;&nbsp;&nbsp;&nbsp;I can't figure out how i can override the default template for aldryn_newsblog.

What I've tried
------------------
* Create a new `project/templates/aldryn_newsblog` folder and put modifiy `base.html` inside.
* Ensure that `django.template.loaders.filesystem.Loader` is loaded before `app_directories.Loader` and before `aldryn_boilerplates`
* I understand `aldryn_newsblog` use `aldryn_boilerplates` and i've read the docs for aldryn_boilerplates as well. You explain how to integrate boilerplate in a new app but not how we can override/extend the base boilerplate.

What I want
---------------
* Is this a stupid idea to do that ? Can i achieve that ?
* The documentation should clearly state if we can override base template (as we can with any other django app) and how we can do it.

By now i don't know how to do it, that's why i request for assistance here. If someone explain me, I could write the docs.

BTW, many thanks for all your great work.

Regards,

**Comment by kittles** [comment]
did you make any progress on this? i would like to do the same thing

**Comment by evildmp** [comment]
@kittles and @vdnclodio I am sorry that this hasn't been answered yet. There's obviously a broken link in our chain of communication with the community. It's late at night here in western Europe, but I promise to have an answer some time tomorrow.

**Comment by FinalAngel** [comment]
@vdnclodio @kittles you should be able to copy the entire ``aldryn_newsblog`` (https://github.com/aldryn/aldryn-newsblog/tree/master/aldryn_newsblog/boilerplates/bootstrap3/templates/aldryn_newsblog) folder into your ``templates`` eg: ``templates/aldryn_newsblog`` and change the templates according to your needs and remove files that are unchanged (to keep the original).

There is no other magic involved. aldryn_bootstrap just makes sure that the correct boilerplate templates are picked within ``boilerplates/***`` but if you have any templates in your personal template folder, they should be overridden.

If this is not the case, the ordering of the template loaders might be off. Let me know if that helps, otherwise I need to do more deeper testing.

**Comment by bartmika** [comment]
Wow great job @vdnclodio with the research, this helps me. I would like to also second this ticket. I am a novice and there's no documentation on how to override the theme/template/etc for customization that I can find in this project.

Please developers of Django-CMS, may you please provide a detailed tutorial on how to do this? I see @FinalAngel added a good write up but there still needs to be a page in the documentation of how to do it.

**Comment by rodolfomartinez** [comment]
+1

**Comment by bartmika** [comment]
Hi @FinalAngel, your solution helped me get it working! Thank you very much!! :+1: 

May I kindly ask someone on your dev team to update the documentation to include more-or-less what @FinalAngel wrote for a "HOWTO: Customize the template" sort of article for this project? By doing this it'll immensely help newbies (like myself) with getting Django-CMS up and running quickly. 

Honestly, if you could include an article on how to customize the blog template  in the main django-cms.org documentation, that would help a lot! Best part is you'll be showcasing/explaining the ** aldryn_bootstrap** module and how it all works together. 

Thank you!

**Comment by FinalAngel** [comment]
@bartmika there is currently heavy progress on how to do this in the current develop branch. @evildmp can you confirm that this will / or is covered as well?

**Comment by victor7891** [comment]
@FinalAngel Thank you so much !
I had the same problem but with others Aldryn addons and now it's solved.
Thanks a lot !

**Comment by FinalAngel** [comment]
you are very welcome @victor7891

**Comment by dmk12** [comment]
@FinalAngel dude, seriously, thank you!

**Comment by phares** [comment]
@FinalAngel worked, thanks

**Comment by dgraydesign** [comment]
I'm having this same issue. I've added the template folder from the repo to my project's templates folder, but they're not overriding the blog templates. Is there any documentation on this anywhere?
