### ISSUE TITLE
Creation Wizard - weird autoback

### ISSUE THREAD

**Issue by Neuronus** [aldryn/aldryn-newsblog#347]
I have weird bug - when I try to create Aldryn NewsBlog article, and choose app config from dropdown list - wizard automagicly go back to main window (wizard main) - so I can't use wizard for any newsblog articles.

**Comment by mkoistinen** [comment]
Please try this with version 1.0.12 released yesterday. Thank you!

**Comment by Neuronus** [comment]
Now it work perfectly.

Some other frontend bugs I'll post later - I hope next version will be focused on front stuff.
