### ISSUE TITLE
No content field

### ISSUE THREAD

**Issue by krisfields** [aldryn/aldryn-newsblog#350]
When I go to add/edit an article, there's no content field.  Everything else seems to work.  You can add pages, view them, edit then, ect..., but they have no content.  And as far as I can tell, there's no way to add content.  I feel like I'm missing something simple, but I have no idea what.  There's a title, lead_in, featured image, ect..., but no way to add content.

Using version 1.0.12, with Django 1.8.8 and Django CMS 3.2.0

Any help would be greatly appreciated.

**Comment by mkoistinen** [comment]
Aldryn NewsBlog uses a "Placeholder Field" to hold the content, this allows the content manager to insert any plugin they like for the content so, text, video, images, maps, etc. all can be part of the article's content.

To add this content, create your article, then when viewing it, switch to "Structure" mode in the CMS, this will display the available placeholders. Add your content to the one labeled: newsblog_article_content.

Enjoy!

**Comment by FabrizioA** [comment]
Hi @mkoistinen , can I add more then one article's placeholders? Thank you.
