### ISSUE TITLE
Sitemaps

### ISSUE THREAD

**Issue by rgcarrasqueira** [aldryn/aldryn-newsblog#369]
Hi!

I would like to know how to add the articles in the sitemap if the blog is a part of the website developed using django-cms?

Thanks

**Comment by rgcarrasqueira** [comment]
Found a solution for that:

Open the urls.py at root of your project

First of all import the correct library to use the Sitemap direct from aldryn newsblog

```
from cms.sitemaps import CMSSitemap
from aldryn_newsblog.sitemaps.sitemap import NewsBlogSitemap
````

After the place where you define the urlpatterns, do:

```
sitemaps = {
    'cmspages': CMSSitemap,
}

for lang, _ in settings.LANGUAGES:
    sitemaps['newsblog-%s' % lang] = NewsBlogSitemap(language=lang)

urlpatterns += patterns('django.contrib.sitemaps.views',
                        url(r'^sitemaps\.xml$', 'sitemap', {'sitemaps': sitemaps}),
                        )
```

I hope that helps everybody!

Cheers from Brasil

Rogério Carrasqueira

**Comment by mwenom** [comment]
Dont work.

**Comment by treavis** [comment]
Seems to work for me.
