### ISSUE TITLE
NoReverseMatch exception raised : u'articles' is not a registered namespace

### ISSUE THREAD

**Issue by yboussard** [aldryn/aldryn-newsblog#432]
When I try a view on a fresh article NoReverseMatch exception is raised.
articles is the namespace that I declare on app configuration.

Environment:
Request Method: GET
Request URL: http://localhost:8000/admin/r/51/4/

Django Version: 1.8.15
Python Version: 2.7.3
Installed Applications:
('djangocms_admin_style',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.admin',
 'django.contrib.sites',
 'django.contrib.sitemaps',
 'django.contrib.staticfiles',
 'django.contrib.messages',
 'cms',
 'menus',
 'sekizai',
 'treebeard',
 'djangocms_text_ckeditor',
 'filer',
 'reversion',
 'easy_thumbnails',
 'djangocms_column',
 'djangocms_link',
 'cmsplugin_filer_file',
 'cmsplugin_filer_folder',
 'cmsplugin_filer_image',
 'cmsplugin_filer_utils',
 'djangocms_style',
 'djangocms_snippet',
 'djangocms_googlemap',
 'djangocms_video',
 'aldryn_apphooks_config',
 'aldryn_boilerplates',
 'aldryn_categories',
 'aldryn_common',
 'aldryn_newsblog',
 'aldryn_people',
 'aldryn_reversion',
 'aldryn_translation_tools',
 'parler',
 'sortedm2m',
 'taggit',
 'compressor',
 )
Installed Middleware:
('cms.middleware.utils.ApphookReloadMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'cms.middleware.user.CurrentUserMiddleware',
 'cms.middleware.page.CurrentPageMiddleware',
 'cms.middleware.toolbar.ToolbarMiddleware')

Traceback:
File "/opt/xxx/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/opt/xxx/local/lib/python2.7/site-packages/django/contrib/admin/sites.py" in wrapper
  254.                 return self.admin_view(view, cacheable)(*args, **kwargs)
File "/opt/xxx/local/lib/python2.7/site-packages/django/utils/decorators.py" in _wrapped_view
  110.                     response = view_func(request, *args, **kwargs)
File "/opt/xxxx/local/lib/python2.7/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
  57.         response = view_func(request, *args, **kwargs)
File "/opt/xxx/local/lib/python2.7/site-packages/django/contrib/admin/sites.py" in inner
  233.             return view(request, *args, **kwargs)
File "/opt/xxx/local/lib/python2.7/site-packages/django/contrib/contenttypes/views.py" in shortcut
  31.     absurl = get_absolute_url()
File "/opt/xxx/local/lib/python2.7/site-packages/aldryn_newsblog/models.py" in get_absolute_url
  192.             return reverse('{0}article-detail'.format(namespace), kwargs=kwargs)
File "/opt/xxx/local/lib/python2.7/site-packages/django/core/urlresolvers.py" in reverse
  574.                                          key)

Exception Type: NoReverseMatch at /admin/r/51/4/
Exception Value: u'articles' is not a registered namespace

Is there a bug or a mistake in configuration ?

**Comment by yboussard** [comment]
I try also with a fresh install on https://control.aldryn.com/control/.
Same error !
link : https://test-youyou-stage.us.aldryn.io/en/admin/r/56/1/.
Extension seems not work.

**Comment by czpython** [comment]
Hello @yboussard,
This error happens because you've not attached the blog apphook to a page ([docs](http://docs.django-cms.org/en/stable/introduction/apphooks.html#apply-the-apphook-to-a-page)), so the blog urls are never loaded.

Please create a cms Page, edit it's Advanced settings and select "NewsBlog" in the **Application** field dropdown. Save and then publish.

**Comment by yboussard** [comment]
Thanks a lot. It's work now.
