### ISSUE TITLE
This QueryDict instance is immutable

### ISSUE THREAD

**Issue by vutrongvu** [aldryn/aldryn-newsblog#481]
When create new page and save advanced-settings. it display error 'AttributeError at /admin/cms/page/7/advanced-settings/'.
Detail: 
AttributeError
This QueryDict instance is immutable
/usr/local/lib/python3.5/site-packages/django/http/request.py in _assert_mutable, line 431
/usr/local/bin/python
3.5.4
['/app',  '/usr/local/lib/python35.zip',  '/usr/local/lib/python3.5',  '/usr/local/lib/python3.5/plat-linux',  '/usr/local/lib/python3.5/lib-dynload',  '/usr/local/lib/python3.5/site-packages']
Wed, 31 Jan 2018 03:42:54 +0000

python: 3.5
Django: 1.11.5
aldryn-newsblog 2.0.0

**Comment by plamen-nikolov** [comment]
It's an issue related to Django-CMS

https://github.com/divio/django-cms/issues/6035

You can checkout to the fix.

**Comment by czpython** [comment]
Fixed by https://github.com/divio/django-cms/issues/6035
