### ISSUE TITLE
Create button on toolbar does not contain "Article" option

### ISSUE THREAD

**Issue by geoidesic** [aldryn/aldryn-newsblog#492]
I've followed the instructions here:
http://aldryn-newsblog.readthedocs.io/en/latest/introduction.html#django-cms-setup

I'm able to create new articles via the main admin interface (as shown). 

<img width="1379" alt="screen shot 2018-05-16 at 11 29 55 am" src="https://user-images.githubusercontent.com/4637995/40112010-8b00f7ec-58fc-11e8-949b-b371d2d27bc0.png">

However the docs here suggest that one should be able to create a new article via the toolbar also, which isn't working – I don't get the "Article" option, just the standard cms options.

<img width="1138" alt="screen shot 2018-05-16 at 11 28 56 am" src="https://user-images.githubusercontent.com/4637995/40111955-5f489d3a-58fc-11e8-9a14-4ceb93953baf.png">

**Comment by toffi9** [comment]
I assume that you are superuser so you have proper permissions, so the problem here could be that newsblog didn't "see" added apphook to the page.  Right now you have apphook added to homepage, yes? Maybe try to create another page and add apphook to it.

**Comment by geoidesic** [comment]
Seems to be working now... although it seems to have replaced the "Create sub-page" option in the `Create` modal. Not sure what kick-started it. Perhaps it was restarting `runserver`.

<img width="1138" alt="screen shot 2018-05-16 at 3 43 05 pm" src="https://user-images.githubusercontent.com/4637995/40124200-f003fdec-591f-11e8-9eac-6ab41d9bb4b4.png">
