### ISSUE TITLE
djangocms-link 2.2.1 breaks NewsBlog

### ISSUE THREAD

**Issue by MacLake** [aldryn/aldryn-newsblog#503]
After updating djangocms-link to version  2.2 or 2.2.1 news pages with links made with djangocms-link break:

> # AttributeError
> ## 'NoneType' object has no attribute 'node'

> 
> Request Method: 	GET
> Request URL: 	http://0.0.0.0:8004/de/news-de/abstract-jetzt-einreichen/
> Django Version: 	1.11.16
> Exception Type: 	AttributeError
> Exception Value: 	 'NoneType' object has no attribute 'node'
>

**Comment by vThaian** [comment]
Please @MacLake upgrade version of your `djangocms-link` to `2.2.2`

**Comment by MacLake** [comment]
@vThaian Thanks! So I should have reported this issue in djangocms-link. Anyway, you’ve found it also here.
