### ISSUE TITLE
Better model/attribute names

### ISSUE THREAD

**Issue by mikek** [aldryn/aldryn-newsblog#67]
I am sorry to bring this up again, but if the app is going to be an example, this is something to consider.
Since namespace is not the only thing that NewsBlogConfig model can store... what is the better name for a `namespace`  FK? `app_config` or `app_hook_config` or just `config`? @yakky what is your preference? Doing it early will be less painful.

I've also tried renaming `Article` to `Entry` (as a more general name for bog post and news article). Both Django and South migrations are straightforward, renaming templates and all context variables was also possible. The thing that have eventually stopped me was a huge number of `article` mentions in the test suite =) This would also affect any project already using the app a lot. `Article` is not a that bad name after all, so renaming a model seems not to be worth it.

**Comment by yakky** [comment]
probably ``app_config`` is the most sensible as it's kind of self explanatory

**Comment by mikek** [comment]
Implemented in #68
