### ISSUE TITLE
Per app instance number of items per page

### ISSUE THREAD

**Issue by mikek** [aldryn/aldryn-newsblog#76]
Plan:

  * Extend `NewsBlogConfigForm` to contain (optional?) `paginate_by` field
  * Add it to `NewsBlogConfigAdmin.get_config_fields()` as `'config.paginate_by'`
  * Replace `settings.ALDRYN_NEWSBLOG_PAGINATE_BY` usage with this field (with fallback to settings)
  * Add, adjust tests

**Comment by mkoistinen** [comment]
Duplicate of #85, closed by #102
