### ISSUE TITLE
Article fields in the wrong language are getting indexed

### ISSUE THREAD

**Issue by mikek** [aldryn/aldryn-newsblog#79]
At [search_indexes.py](https://github.com/aldryn/aldryn-newsblog/blob/master/aldryn_newsblog/search_indexes.py) there are `safe_translation_getter()` calls without current language argument (and it looks like _parler_ does not try to detect the current language inside that method either). So, article's filelds translated in first available language are sometimes indexed in the _Solr_ core for another language.
The _aldryn-search_ was built with _hvad_ in mind, so we probably need to take some extra steps in index methods to properly index translatable models.
@yakky, can you try to reproduce this and adjust the index?
CC: @czpython @intellectronica

**Comment by yakky** [comment]
On it

**Comment by yakky** [comment]
@mikek could you check 0c314e7?

**Comment by mkoistinen** [comment]
@mike can you advise?

**Comment by mkoistinen** [comment]
@mikek Is this still an issue? Need your feedback here.

**Comment by mikek** [comment]
@mkoistinen, IIRC, I was not able to test (or id did not fix the issue for me) 0c314e7 and it can not be cleanly applied to master now. @chronossc is now working on search related code in our project, he might know for sure if newsblog search configuration is up to date.

**Comment by mkoistinen** [comment]
@chronossc did you already fix this issue? If so, can we close this?

**Comment by mkoistinen** [comment]
Closing due to age, please re-open if this issue still exists
