### ISSUE TITLE
We should not have a default namespace created in migrations

### ISSUE THREAD

**Issue by mkoistinen** [aldryn/aldryn-newsblog#82]

**Comment by czpython** [comment]
@mikek what was the reason for this? (```latest_entries_plugin_default_namespace```)

**Comment by mkoistinen** [comment]
@mikek, we'd like to fix and close this. Comment?

**Comment by mikek** [comment]
It was created as a part of migration process, as app_config was going to be non-nullable, and it is now.
I am not sure how just dropping the migration would affect existing installations (if there are any). @mkoistinen were you going to replace it by something else?

**Comment by mkoistinen** [comment]
Closed by #130.
